### ISSUE TITLE
Invalid string are allowed into forms

### ISSUE THREAD

**Issue by foodalertscal** [MikeElofson/FoodAlertsCal#4]
Forms do not prevent against sql injection. Need to switch code to use MySQLi instead of strings.

References:
sessionlogin.php (already converted logins)
https://secure.php.net/manual/en/class.mysqli-stmt.php
https://secure.php.net/manual/en/mysqli-stmt.bind-result.php
https://secure.php.net/manual/en/mysqli-stmt.fetch.php

**Comment by foodalertscal** [comment]
Fixed login form, should model off of this. 

https://github.com/MikeElofson/FoodAlertsCal/commit/fa095e58463db767466b26205e7d62c2ecfb9ba7

**Comment by MikeElofson** [comment]
Fixed login form, should model off of this.

https://github.com/MikeElofson/FoodAlertsCal/commit/fa095e58463db767466b26205e7d62c2ecfb9ba7

**Comment by MikeElofson** [comment]
Changed all sql to use prepared statements. Should prevent sql injection attacks

https://github.com/MikeElofson/FoodAlertsCal/commit/1eb1821b5416319d83eaa32ad31a24ff073bc672
